TOMCAT_VERSION: 9.0.73
TOMCAT_URL: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ TOMCAT_VERSION }}/bin/apache-tomcat-{{ TOMCAT_VERSION }}.tar.gz"
TOMCAT_HOME: "/opt/apache-tomcat-{{ TOMCAT_VERSION }}"
